
USE artiscene_db;

INSERT into tags (tag_name) VALUES ("acrylic");
INSERT into tags (tag_name) VALUES ("watercolor");
INSERT into tags (tag_name) VALUES ("charcoal");
INSERT into tags (tag_name) VALUES ("ink");
INSERT into tags (tag_name) VALUES ("color");
INSERT into tags (tag_name) VALUES ("black and white");
INSERT into tags (tag_name) VALUES ("prints");
INSERT into tags (tag_name) VALUES ("woodcut");
INSERT into tags (tag_name) VALUES ("graphite");
INSERT into tags (tag_name) VALUES ("prisma");
INSERT into tags (tag_name) VALUES ("chalk");
INSERT into tags (tag_name) VALUES ("conte");
INSERT into tags (tag_name) VALUES ("gouache");
INSERT into tags (tag_name) VALUES ("clay");
INSERT into tags (tag_name) VALUES ("pottery");
INSERT into tags (tag_name) VALUES ("marker");
INSERT into tags (tag_name) VALUES ("oil");
INSERT into tags (tag_name) VALUES ("tempera");
INSERT into tags (tag_name) VALUES ("pastel");
INSERT into tags (tag_name) VALUES ("fabric");
INSERT into tags (tag_name) VALUES ("scratchboard");
INSERT into tags (tag_name) VALUES ("wood");
INSERT into tags (tag_name) VALUES ("wire");
INSERT into tags (tag_name) VALUES ("glass");
INSERT into tags (tag_name) VALUES ("metal");
INSERT into tags (tag_name) VALUES ("plaster");
INSERT into tags (tag_name) VALUES ("blacklight");
INSERT into tags (tag_name) VALUES ("magna");
INSERT into tags (tag_name) VALUES ("stencil");
INSERT into tags (tag_name) VALUES ("enamel");
INSERT into tags (tag_name) VALUES ("ink wash");
INSERT into tags (tag_name) VALUES ("stippling");
INSERT into tags (tag_name) VALUES ("line work");
INSERT into tags (tag_name) VALUES ("hatching");
INSERT into tags (tag_name) VALUES ("traditional");
INSERT into tags (tag_name) VALUES ("mosaic");
INSERT into tags (tag_name) VALUES ("photography");
INSERT into tags (tag_name) VALUES ("dark room");
INSERT into tags (tag_name) VALUES ("computer printing");
INSERT into tags (tag_name) VALUES ("engraving");
INSERT into tags (tag_name) VALUES ("lithographic");
INSERT into tags (tag_name) VALUES ("etching");
INSERT into tags (tag_name) VALUES ("print making");
INSERT into tags (tag_name) VALUES ("relief printing");
INSERT into tags (tag_name) VALUES ("screen printing");
INSERT into tags (tag_name) VALUES ("comic");
INSERT into tags (tag_name) VALUES ("found objects");
INSERT into tags (tag_name) VALUES ("textile");
INSERT into tags (tag_name) VALUES ("commissioned");
INSERT into tags (tag_name) VALUES ("w.i.p");
INSERT into tags (tag_name) VALUES ("graphic design");
INSERT into tags (tag_name) VALUES ("performance");
INSERT into tags (tag_name) VALUES ("photoshop");
INSERT into tags (tag_name) VALUES ("collage");
INSERT into tags (tag_name) VALUES ("amateur");
INSERT into tags (tag_name) VALUES ("professional");
INSERT into tags (tag_name) VALUES ("graffiti");
INSERT into tags (tag_name) VALUES ("mural");
INSERT into tags (tag_name) VALUES ("street art");
INSERT into tags (tag_name) VALUES ("crayon");
INSERT into tags (tag_name) VALUES ("sand");
INSERT into tags (tag_name) VALUES ("color pencil");
INSERT into tags (tag_name) VALUES ("figure drawing");
INSERT into tags (tag_name) VALUES ("nude");
INSERT into tags (tag_name) VALUES ("realism");
INSERT into tags (tag_name) VALUES ("abstract");
INSERT into tags (tag_name) VALUES ("direct observation");
INSERT into tags (tag_name) VALUES ("surrealism");
INSERT into tags (tag_name) VALUES ("political");
INSERT into tags (tag_name) VALUES ("calligraphy");
INSERT into tags (tag_name) VALUES ("illustration");
INSERT into tags (tag_name) VALUES ("fine art");
INSERT into tags (tag_name) VALUES ("fan art");
INSERT into tags (tag_name) VALUES ("tapestry");
INSERT into tags (tag_name) VALUES ("conceptual");
INSERT into tags (tag_name) VALUES ("cartoon");
INSERT into tags (tag_name) VALUES ("ceramic");
INSERT into tags (tag_name) VALUES ("canvas");
INSERT into tags (tag_name) VALUES ("fashion");
INSERT into tags (tag_name) VALUES ("tattoo");
INSERT into tags (tag_name) VALUES ("body mod");
INSERT into tags (tag_name) VALUES ("body paint");
INSERT into tags (tag_name) VALUES ("mixed");
INSERT into tags (tag_name) VALUES ("sculpture");
INSERT into tags (tag_name) VALUES ("portrait");
INSERT into tags (tag_name) VALUES ("painting");
INSERT into tags (tag_name) VALUES ("3d");
INSERT into tags (tag_name) VALUES ("digital");


